### ISSUE TITLE
Implement payees functionality

### ISSUE THREAD

**Issue by frosklis** [frosklis/dinero-rs#31]
```payee``` is one of the directives in the original [ledger-cli](https://www.ledger-cli.org) and I intend to replicate the functionality it provides but also diverge a little bit because of some nuances I don't like.

What I intend to keep because I actually use it and find extremely useful:
- [x] Reassign payees based on aliases (payee directive)
- [x] ...aliases that can be regular expressions (payee directive)
- [ ] reassign postings in unknown accounts to other accounts based on payees (account directive)

But I plan on eventually diverging in some aspects.

First of all, the description of a transaction should not be the payee.
The description should be exactly that: a description. Then, with the ```@``` sign you could get specific about the payee.
- [x] get the payee in the description using the ```@``` sign.

Second, the payee is a posting concept. By definition, in a double-entry accounting system, the payee is the *owner* of the account. For example:

```ledger
2021-02-14 * Flowers
    Expenses:Gifts               30.00 €
    Assets:Checking account
```
In this simple example, in all truth we don't know the payee for the flowers (where they were bought). Ledger-cli interpretes ```flowers ``` as the payee both of the expense and the assett account. Doesn't make much sense to me. You could write, to be explicit:

```ledger
2021-02-14 * Flowers
    Expenses:Gifts               30.00 €; Payee: Flower shop
    Assets:Checking account             ; Payee: me
```

But I think there is a better solution if you just include an owner for each account in the account directive with sensible defaults: asset and liability accounts are owned by *me*, whereas expenses and income vary and need to be specified on a posting per posting basis. All of this could be inferred. And the syntax would look like this:

```ledger
2021-02-14 * Flowers @ Flower shop
    Expenses:Gifts               30.00 €
    Assets:Checking account             
```

**Comment by tbm** [comment]
>  The description should be exactly that: a description. Then, with the @ sign you could get specific about the payee.

hledger uses the pipe symbol `|` to separate payee and description: https://hledger.org/journal.html#payee-and-note

I think you should adopt the same instead of introducing yet another syntax.

**Comment by frosklis** [comment]
> hledger uses the pipe symbol `|` to separate payee and description: https://hledger.org/journal.html#payee-and-note

Yep, that makes sense. Really need to look into that to foster compatibility. However, I find it a bit add that you use `@` for searching payees and introduce this symbol.

I've got most payee functionality implemented in the ```search``` branch, but I need to clean-up the code, as it's getting messy.... and slow to run in my personal ledger (26K postings according to ```ledger stats```).
